name: 'Stale PR handler'
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4  #v4 is the maximum supported by our github version
        id: stale-pr
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          # Configure Issues
          days-before-issue-stale: 180
          days-before-issue-close: 30
          stale-issue-message: 'This Issue is stale because it has been open for 6 months with no activity. Remove stale label or comment or this issue will be closed in 30 days.'
          close-issue-message: 'This Issue has been closed due to inactivity.'
          # Configure PRs
          stale-pr-message: 'This PR is stale because it has been open 20 days with no activity. Remove stale label or comment or this PR will be closed in 10 days.'
          close-pr-message: 'This PR has been closed and its branch deleted due to inactivity.'
          days-before-pr-stale: 30
          days-before-pr-close: 15
          exempt-pr-labels: 'blocked,must,should,keep'
          delete-branch: true
      - name: Print outputs
        run: echo ${{ join(steps.stale.outputs.*, ',') }}
